packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  zod: ^4.1.5
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
  "@clerk/nextjs": ^6.23.0
  superjson: ^2.2.2
  ai: ^4.3.16
  "@openrouter/ai-sdk-provider": ^0.7.1
  "@t3-oss/env-nextjs": ^0.13.6
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
